# .sops.yaml
keys:
  - &personalmbp age1ca6dvkttshcs4ealm8nttymp92lmqe62cvgxrgnkkstygu4ujg9qsjfexq
creation_rules: 
  - path_regex: secrets/secrets.yaml$
    key-groups:
      - age:
        - *personalmbp
