{
  imports = [
    ./alpha.nix
    ./bufferline.nix
    ./cmp.nix
    ./colorizer.nix
    ./comment.nix
    ./copilot.nix
    ./dressing.nix
    ./efmls.nix
    ./flash.nix
    ./gitsigns.nix
    ./image.nix
    ./lsp-config.nix
    ./lspsaga.nix
    ./lualine.nix
    ./magma.nix
    ./mini.nix
    ./misc.nix
    ./neoscroll.nix
    ./neotree.nix
    ./notify.nix
    ./obsidian.nix
    ./project.nix
    ./statuscol.nix
    ./telescope.nix
    ./todo-comments.nix
    ./toggleterm.nix
    ./treesitter.nix
    ./twilight.nix
    ./ufo.nix
    ./which-key.nix
  ];
}
